### PR TITLE
Enable CORS to support frontend apps

### PR DESCRIPTION
**Pull request by rafenden**
Enable CORS support to allow frontend apps to query Camunda endpoints without the need for unnecessary proxy.

### CODE REVIEW

**Comment by pixie79** [comment]
This should not be required, it is not needed in other places. I think you will find the issue is probably with the redirect urls and web origins being set correct within Keycloak for both the engine and ui.

**Comment by rafenden** [comment]
> This should not be required, it is not needed in other places. I think you will find the issue is probably with the redirect urls and web origins being set correct within Keycloak for both the engine and ui.

@pixie79 It's not required, but it saves the hassle of creating proxy endpoints on all front-end apps that are getting data from this service.

I'm not sure what do you mean by the issues with the urls from Keycloak, could you elaborate on that, please?

**Comment by pixie79** [comment]
redirect-urls and web-origins are two client settings in Keycloak. They need to be set correctly for CORS to work

**Comment by rafenden** [comment]
> redirect-urls and web-origins are two client settings in Keycloak. They need to be set correctly for CORS to work

What do you mean by "set correctly"?

**Comment by pixie79** [comment]
I mean that someone needs to review keycloak and check the settings are appropriate to allow cors to work. Checking what the settings should be for cors. All i can say is i have seen this as an issue with other services.

**Comment by rafenden** [comment]
> I mean that someone needs to review keycloak and check the settings are appropriate to allow cors to work. Checking what the settings should be for cors. All i can say is i have seen this as an issue with other services.

It worked fine on localhost, so I guess the only way to find this out is to deploy the service to the dev environment and test it thoroughly.

**Comment by pixie79** [comment]
The frontend proxy is not additional it is there by design - it should not be removed

**Pull request closed without merging**
